name: Build Tag Release

on:
  push:
    branches: [ master ]

jobs:

  build:
    name: Build, tag, release
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go mod download

    - name: Build
      run: go build -v .
      
    - uses: actions/checkout@master
    - name: Bump version and push tag
      if: ${{ success() }}
      uses: mathieudutour/github-tag-action@v4
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      id: create_tag
      
    - name: Create Release
      if: ${{ success() }}
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        tag_name: ${{ format('simple-iam-vault-cli-{0}-{1}', steps.create_tag.outputs.new_tag, github.sha) }}
        release_name: Release ${{ steps.create_tag.outputs.new_tag }}
        draft: false
        prerelease: false
      id: create_release

    - name: Build and push release artifact linux/amd64
      if: ${{ success() }}
      uses: wangyoucao577/go-release-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: linux
        goarch: amd64
